name: Generate GitHub Metrics

on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      -
        # https://github.com/lowlighter/metrics/tree/master?tab=readme-ov-file#-setup
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: ${{ github.repository_owner }}
          template: classic
          output_action: commit
          committer_branch: output
          
          base: header, activity, repositories

          config_timezone: Europe/Berlin
          
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          
          plugin_repositories: yes
          
          plugin_stargazers: yes
          plugin_stargazers_charts: yes
          plugin_stargazers_charts_type: classic
