name: Generate GitHub Metrics

on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      -
        # https://github.com/lowlighter/metrics/tree/master?tab=readme-ov-file#-setup
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: ${{ github.repository_owner }}
          template: classic
          output_action: commit
          committer_branch: output
          
          base: header, activity, community, repositories, metadata
          #base: header
          #plugin_isocalendar: yes
          #plugin_languages: yes
          #plugin_stars: yes
          #config_order: base.header, isocalendar, languages, stars
          
          config_display: columns
          config_timezone: Europe/Berlin
          
          plugin_followup: yes
          plugin_followup_archived: yes
          plugin_followup_sections: repositories
          
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          
          plugin_lines: yes
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: base
          
          plugin_reactions: yes
          plugin_reactions_display: absolute
          plugin_reactions_limit: 200
          plugin_reactions_limit_discussions: 100
          plugin_reactions_limit_discussions_comments: 100
          plugin_reactions_limit_issues: 100
          
          plugin_repositories: yes
          
          plugin_stargazers: yes
          plugin_stargazers_charts: yes
          plugin_stargazers_charts_type: classic
