# GitHub Action for generating a snake game/animation from a GitHub user's contributions graph
name: Generate Snake Animation

on:
  schedule:
    # Execute every 24 hours
    - cron: "* */24 * * *"
  # This command allows us to run the GitHub Action manually from the "Actions" tab at any time
  workflow_dispatch:

# The sequence of job runs in this workflow
jobs:
  snake-animation:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    # Steps representing a sequence of tasks that will be executed as part of this job
    steps:
      -
        # https://github.com/Platane/snk?tab=readme-ov-file#usage
        name: Generate snake animation
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/snake-animation.svg
            dist/snake-animation-dark.svg?palette=github-dark
      -
        # https://github.com/crazy-max/ghaction-github-pages/tree/dev?tab=readme-ov-file#usage
        name: Deploy to GitHub Pages or Push the content of <build_dir> to <target_branch>
        uses: crazy-max/ghaction-github-pages@v4
        with:
          # The content will be available at https://raw.githubusercontent.com/<github_username>/<repository>/<target_branch>/<file> , or as GitHub Pages
          target_branch: output
          build_dir: dist
          author: Hua-Ming Huang (huaming.huang.tw@gmail.com)
          committer: Hua-Ming Huang (huaming.huang.tw@gmail.com)
          commit_message: Update snake animation
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
