# GitHub Action for generating a snake game/animation from a GitHub user's contributions graph
name: Generate Snake Animation

on:
  schedule:
    # Execute every 24 hours
    - cron: "* */24 * * *"
  # This command allows us to run the GitHub Action manually from the "Actions" tab at any time
  workflow_dispatch:

# The sequence of job runs in this workflow
jobs:
  job1:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    # Steps representing a sequence of tasks that will be executed as part of this job
    steps:
      -
        name: Generate snake animation
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/snake-animation.svg
            dist/snake-animation-dark.svg?palette=github-dark&color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
      -
        name: Deploy to GitHub Pages or Push the content of <build_dir> to a branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          # The content will be available at https://raw.githubusercontent.com/<github_username>/<repository>/<target_branch>/<file> , or as GitHub Pages
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
