# GitHub Action for generating a snake game/animation from a GitHub user's contributions graph
name: Generate Snake Animation

on:
  # Execute every 12 hours
  schedule: [{cron: "* */12 * * *"}]
  # This command allows us to run the GitHub Action manually from the "Actions" tab at any time
  workflow_dispatch:
  push: {branches: [main, master]}

# The sequence of job runs in this workflow
jobs:
  snake-animation:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    # Steps representing a sequence of tasks that will be executed as part of this job
    steps:
      -
        # https://github.com/Platane/snk?tab=readme-ov-file#usage
        name: Generate snake animation
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/snake-animation.svg
            dist/snake-animation-dark.svg?palette=github-dark
