# GitHub Action for generating a snake game/animation from a GitHub user's contributions graph
name: Generate Snake Animation

on:
  schedule:
    # Execute every 24 hours
    - cron: "* */24 * * *"

  # This command allows us to run the GitHub Action manually from the "Actions" tab at any time
  workflow_dispatch:
    
# The sequence of job runs in this workflow
jobs:
  
  job1:
  
    runs-on: ubuntu-latest
      
    timeout-minutes: 5
    
    # Steps representing a sequence of tasks that will be executed as part of this job
    steps:
      -
        name: Generate snake animation
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs:
            dist/snake-animation.svg
            dist/snake-animation-dark.svg?palette=github-dark
      -
        name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
